### ISSUE TITLE
Doorbell just keeps ringing on v0.8.1.

### ISSUE THREAD

**Issue by kharder69** [homespun/homebridge-platform-ring-video-doorbell#44] opened 2018-08-24 13:38 UTC
Doorbell keeps ringing every 30 seconds to a minute.

**Comment by Hucksleyy91** [comment] 2018-08-25 01:29
https://youtu.be/0UjJnVE0bZQ
I hope this helps

**Comment by mdrzml** [comment] 2018-08-25 03:18
@Hucksleyy91 does doing this suppress the constant dinging as well?

**Comment by Hucksleyy91** [comment] 2018-08-25 05:00
I don’t have constant dings in my home, it use to work perfectly fine but I think after I changed the name in eve to attempt it to show in the home app it has since never given me a ding in the home app I can only get it to work using the method shown in the video above

**Comment by mdrzml** [comment] 2018-08-25 05:18
@Hucksleyy91 ah that explains it. currently for new installations of the plugin, there will be a continuous ding every 1 minute without us doing anything else.

**Comment by Hucksleyy91** [comment] 2018-08-25 05:38
I once had this working fine the ring button would not show up in the home app but I would still get dings notifications with a photo from a camera in the same HomeKit room as the motion sensor if I tap on it I had 2 way audio and 1 way video as well as buttons to turn lights on or off/open the door or whatever other things in the same room , I was happy with it, The ring had a button and also motion alerts in HomeKit that the Arlo camera I was using did not have to use as a doorbell I’m not sure what it was I done that made it stop showing up but could be because I tried to give it a name in the eve app I’m not sure I don’t want to reset my home to add it again to see if it shows up again.... but then again i won’t use this plugin if it’s not fixed soon so I might give it a go

**Comment by mdrzml** [comment] 2018-08-25 05:50
that is quite insightful. good to know that homekit does combine the motion sensor for ring doorbell to work together with other cameras.

**Comment by Vangel87** [comment] 2018-08-25 13:16
I have the same issue: my Doorbell 2 keeps sending me notifications. I live next to a busy street so maybe it’s a motion sensor alerts? Can you disable motion sensing in this plugin?

**Comment by kharder69** [comment] 2018-08-25 13:18
Unfortunately it’s not the motion sensor causing it.  Another note is that in home app I only see two motion sensors, is that what everyone else sees?  I don’t actually see a doorbell.  Don’t know if there is a different accessory type for it.

Ken

On Aug 25, 2018, at 9:16 AM, Vangel87 <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the same issue: my Doorbell 2 keeps sending me notifications. I live next to a busy street so maybe it’s a motion sensor alerts? Can you disable motion sensing in this plugin?

**Comment by Vangel87** [comment] 2018-08-25 13:34
Ok but it’s a problem with just a current version of this plugin or it was a problem from the beginning? I’m new to this plugin, installed it just an hour ago so sorry for basic questions :)

**Comment by mdrzml** [comment] 2018-08-25 15:30
@Hucksleyy91 the video screencap you posted earlier is from your Arlo camera and not from Ring doorbell right?

**Comment by mrose17** [comment] 2018-08-29 13:38
Duplicate of #43

**Closed by mrose17** 2018-08-29 13:38 UTC
